# HLint configuration file
#
# see `hlint --default` for help
################################

- ignore: { name: "Use <$>" }
- ignore: {
    name: "Use newtype instead of data",
    within: Kore.Definition.Attributes.Base
  }
