name: 'Build + Test'
on:
  pull_request:
  push:
    branches: ['main']

concurrency:
  # head_ref is defined for PRs only, so we use run_id (unique) for
  # the main branch to ensure all commits are built
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  ghc_version: '9.2.5'
  hlint_version: '3.4.1'
  fourmolu_version: '0.8.2.0'
  hpack_version: '0.34.2'

jobs:

  stack:
    name: 'Stack / Unit Tests'
    runs-on: [self-hosted, linux, normal]
    steps:

      - name: 'Checkout Code'
        uses: actions/checkout@v3
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          tag: hs-booster-ci-stack-unit-ubuntu-jammy-${{ github.sha }}
          os: ubuntu
          distro: jammy

      - name: 'Run unit tests'
        run: docker exec -t hs-booster-ci-stack-unit-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'stack test --pedantic'

      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 hs-booster-ci-stack-unit-ubuntu-jammy-${GITHUB_SHA}

  cabal:
    name: 'Cabal / Unit Tests'
    runs-on: [self-hosted, linux, normal]
    steps:

      - 'Checkout Code'
        uses: actions/checkout@v3
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Cache Cabal package database and store'
        uses: actions/cache@v3
        with:
          path: |
            cabal-cache/packages
            cabal-cache/store
          key: cabal-1-${{ runner.os }}-ghc-${{ env.ghc_version }}-${{ hashFiles('hs-backend-booster.cabal') }}
          restore-keys: |
            cabal-1-${{ runner.os }}-ghc-${{ env.ghc_version }}-

      - name: 'Cache Stack root'
        uses: actions/cache@v3
        path: stack-cache
        key: stack-1-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          stack-1-${{ runner.os }}-

      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          tag: hs-booster-ci-cabal-unit-ubuntu-jammy-${{ github.sha }}
          os: ubuntu
          distro: jammy
          docker-run-args: |
            -v cabal-cache/packages:/opt/workspace/.cabal/packages
            -v cabal-cache/store:/opt/workspace/.cabal/store
            -v stack-cache:/opt/workspace/.stack

      - name: 'hpack'
        run: |
          docker exec -t hs-booster-ci-cabal-unit-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'curl -sSL https://github.com/sol/hpack/releases/download/${{ env.hpack_version }}/hpack_linux.gz | gunzip -c > hpack && chmod +x hpack'
          docker exec -t hs-booster-ci-cabal-unit-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c './hpack'

      - name: 'Install tools'
        run: |
          docker exec -t hs-booster-ci-cabal-unit-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'cabal install happy'
          docker exec -t hs-booster-ci-cabal-unit-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'cabal install alex'

      - name: 'Run unit tests'
        run: docker exec -t hs-booster-ci-cabal-unit-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'cabal v2-test --enable-tests --test-show-details=direct'

      - name: 'Configure with profiling'
        run: docker exec -t hs-booster-ci-cabal-unit-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'cabal v2-configure --enable-profiling -f-threaded'

      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 hs-booster-ci-cabal-unit-ubuntu-jammy-${GITHUB_SHA}

  style:
    name: 'Formatting and Style'
    runs-on: [self-hosted, linux, flyweight]
    steps:

      - 'Checkout Code'
        uses: actions/checkout@v3
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          tag: hs-booster-ci-formatting-style-ubuntu-jammy-${{ github.sha }}
          os: ubuntu
          distro: jammy

      - name: 'Install fourmolu'
        # this could be cached but is probably fast anyway
        run: |
          docker exec -t hs-booster-ci-formatting-style-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'curl -sSL https://github.com/fourmolu/fourmolu/releases/download/v${{ env.fourmolu_version }}/fourmolu-${{ env.fourmolu_version }}-linux-x86_64 -o fourmolu && chmod +x fourmolu && ./fourmolu --version'
          docker exec -t hs-booster-ci-formatting-style-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'curl -sSL https://github.com/ndmitchell/hlint/releases/download/v${{ env.hlint_version }}/hlint-${{ env.hlint_version }}-x86_64-linux.tar.gz | tar xvz hlint-${{ env.hlint_version }}/hlint'

      - name: 'Check formatting'
        run: docker exec -t hs-booster-ci-formatting-style-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'PATH=$PWD:$PATH scripts/fourmolu.sh && git diff'

      - name: 'Run hlint'
        run: docker exec -t hs-booster-ci-formatting-style-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'hlint-${{ env.hlint_version }}/hlint -g -j'

      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 hs-booster-ci-formatting-style-ubuntu-jammy-${GITHUB_SHA}
