name: 'Build + Test'
on:
  pull_request:
  push:
    branches: ['main']

concurrency:
  # head_ref is defined for PRs only, so we use run_id (unique) for
  # the main branch to ensure all commits are built
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  ghc_version: '9.2.5'
  hlint_version: '3.4.1'
  fourmolu_version: '0.8.2.0'
  hpack_version: '0.34.2'

jobs:

  stack:
    name: 'Stack / Unit Tests'
    runs-on: [self-hosted, linux, normal]
    steps:

      - name: 'Checkout Code'
        uses: actions/checkout@v3
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Cache Stack root'
        uses: actions/cache@v3
        with:
          path: stack-cache
          key: stack-2-${{ runner.os }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            stack-2-${{ runner.os }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
            stack-2-${{ runner.os }}-${{ hashFiles('stack.yaml') }}
            stack-2-${{ runner.os }}

      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          tag: hs-booster-ci-stack-unit-ubuntu-jammy-${{ github.sha }}
          os: ubuntu
          distro: jammy
          fourmolu: ${{ env.fourmolu_version }}
          hlint: ${{ env.hlint_version }}
          hpack: ${{ env.hpack_version }}
          ghc: ${{ env.ghc_version }}

      - name: 'Run unit tests'
        run: docker exec -t hs-booster-ci-stack-unit-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'stack --system-ghc --stack-root $(pwd)/stack-cache test --pedantic'

      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 hs-booster-ci-stack-unit-ubuntu-jammy-${GITHUB_SHA}

  cabal:
    name: 'Cabal / Unit Tests'
    runs-on: [self-hosted, linux, normal]
    steps:

      - name: 'Checkout Code'
        uses: actions/checkout@v3
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Cache Cabal package database and store'
        uses: actions/cache@v3
        with:
          path: |
            cabal-cache/packages
            cabal-cache/store
          key: cabal-2-${{ runner.os }}-ghc-${{ env.ghc_version }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            cabal-2-${{ runner.os }}-ghc-${{ env.ghc_version }}-

      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          tag: hs-booster-ci-cabal-unit-ubuntu-jammy-${{ github.sha }}
          os: ubuntu
          distro: jammy
          fourmolu: ${{ env.fourmolu_version }}
          hlint: ${{ env.hlint_version }}
          hpack: ${{ env.hpack_version }}
          ghc: ${{ env.ghc_version }}

      - name: 'Run hpack'
        run: |
          docker exec -t hs-booster-ci-cabal-unit-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'hpack'

      - name: 'Build and run unit tests'
        run: |
          docker exec -t hs-booster-ci-cabal-unit-ubuntu-jammy-${GITHUB_SHA} \
            /bin/bash -c 'cabal --store-dir /opt/workspace/cabal-cache/store v2-test --enable-tests --test-show-details=direct'

      - name: 'Configure with profiling'
        run: |
          docker exec -t hs-booster-ci-cabal-unit-ubuntu-jammy-${GITHUB_SHA} \
            /bin/bash -c 'cabal --store-dir /opt/workspace/cabal-cache/store v2-configure --enable-profiling -f-threaded'

      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 hs-booster-ci-cabal-unit-ubuntu-jammy-${GITHUB_SHA}

  style:
    name: 'Formatting and Style'
    runs-on: [self-hosted, linux, normal]
    steps:

      - name: 'Checkout Code'
        uses: actions/checkout@v3
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          tag: hs-booster-ci-formatting-style-ubuntu-jammy-${{ github.sha }}
          os: ubuntu
          distro: jammy
          fourmolu: ${{ env.fourmolu_version }}
          hlint: ${{ env.hlint_version }}
          hpack: ${{ env.hpack_version }}
          ghc: ${{ env.ghc_version }}

      - name: 'Check formatting'
        run: docker exec -t hs-booster-ci-formatting-style-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c './scripts/fourmolu.sh && git diff'

      - name: 'Run hlint'
        run: docker exec -t hs-booster-ci-formatting-style-ubuntu-jammy-${GITHUB_SHA} /bin/bash -c 'hlint -g -j'

      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 hs-booster-ci-formatting-style-ubuntu-jammy-${GITHUB_SHA}
